name: Test, build and release
on: [push]
jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Install check and pkg-config
        run: |
          sudo apt-get update
          sudo apt-get install -y check pkg-config
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Building with check
        run: |
          gcc operations.c check_operations.c -o check_operations $(pkg-config --cflags --libs check)
      - name: Testing with check
        run: |
          ./check_operations
  lint:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install splint
        run: |
          sudo apt-get update
          sudo apt-get install -y splint
      - name: Static analysis
        run: |
          splint --compdef --exportlocal ./simplecalculator.c ./operations.c
      - name: Debug file system
        run: |
          ls -l
          pwd
  building-and-delivery:
    name: Build and delivery
    permissions:
      contents: write
    needs: [unit-test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Building
        run: |
          gcc operations.c simplecalculator.c -o simplecalculator
          echo "AG11M9" > neptun.txt
      - name: Creating tar.gz
        run: |
          tar -czvf simplecalculator.tar.gz simplecalculator neptun.txt
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development build"
          files: |
            simplecalculator.tar.gz
