name: Test, build, and release
on:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Install check and pkg-config
        run: |
          sudo apt-get update
          sudo apt-get install -y check pkg-config
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Building with check
        run: |
          gcc operations.c check_operations.c -o check_operations $(pkg-config --cflags --libs check)
      - name: Testing with check
        run: |
          ./check_operations

  building-and-delivery:
    name: Build and delivery
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Building
        run: |
          gcc operations.c simplecalculator.c -o simplecalculator
      - name: Creating tar.gz
        run: |
          tar -czvf simplecalculator.tar.gz simplecalculator
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: simplecalculator
          path: simplecalculator.tar.gz